#!/bin/bash
# Setup script for AWS Free Tier infrastructure

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${GREEN}╔════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║   Sentra AWS Free Tier Setup               ║${NC}"
echo -e "${GREEN}║   Estimated cost: \$0-5/month               ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════╝${NC}"
echo ""

# Check prerequisites
echo -e "${BLUE}Checking prerequisites...${NC}"

if ! command -v aws &> /dev/null; then
    echo -e "${RED}❌ AWS CLI not found. Install: https://aws.amazon.com/cli/${NC}"
    exit 1
fi
echo -e "${GREEN}✓ AWS CLI installed${NC}"

if ! command -v terraform &> /dev/null; then
    echo -e "${RED}❌ Terraform not found. Install: https://terraform.io/downloads${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Terraform installed${NC}"

# Check AWS credentials
if ! aws sts get-caller-identity &> /dev/null; then
    echo -e "${RED}❌ AWS credentials not configured. Run: aws configure${NC}"
    exit 1
fi

AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
AWS_REGION="${AWS_REGION:-us-east-1}"

echo -e "${GREEN}✓ AWS configured (Account: ${AWS_ACCOUNT_ID})${NC}"
echo ""

# Configuration
PROJECT_NAME="sentra"
BUCKET_NAME="${PROJECT_NAME}-terraform-state-free"
TABLE_NAME="${PROJECT_NAME}-terraform-locks"
KEY_NAME="${PROJECT_NAME}-free-key"

echo -e "${YELLOW}Configuration:${NC}"
echo "  Project:    $PROJECT_NAME"
echo "  Region:     $AWS_REGION"
echo "  S3 Bucket:  $BUCKET_NAME"
echo "  Key Name:   $KEY_NAME"
echo ""

read -p "Continue? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
fi

# Step 1: Create S3 bucket
echo ""
echo -e "${BLUE}Step 1/4: Creating S3 bucket for Terraform state...${NC}"

if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
    echo -e "${YELLOW}⚠ Bucket already exists${NC}"
else
    if [ "$AWS_REGION" == "us-east-1" ]; then
        aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$AWS_REGION"
    else
        aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$AWS_REGION" \
            --create-bucket-configuration LocationConstraint="$AWS_REGION"
    fi

    aws s3api put-bucket-versioning --bucket "$BUCKET_NAME" \
        --versioning-configuration Status=Enabled

    aws s3api put-bucket-encryption --bucket "$BUCKET_NAME" \
        --server-side-encryption-configuration '{
            "Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]
        }'

    echo -e "${GREEN}✓ S3 bucket created${NC}"
fi

# Step 2: Create DynamoDB table
echo ""
echo -e "${BLUE}Step 2/4: Creating DynamoDB table for state locking...${NC}"

if aws dynamodb describe-table --table-name "$TABLE_NAME" --region "$AWS_REGION" 2>/dev/null; then
    echo -e "${YELLOW}⚠ DynamoDB table already exists${NC}"
else
    aws dynamodb create-table \
        --table-name "$TABLE_NAME" \
        --attribute-definitions AttributeName=LockID,AttributeType=S \
        --key-schema AttributeName=LockID,KeyType=HASH \
        --billing-mode PAY_PER_REQUEST \
        --region "$AWS_REGION"

    echo -e "${GREEN}✓ DynamoDB table created${NC}"
fi

# Step 3: Create EC2 key pair
echo ""
echo -e "${BLUE}Step 3/4: Creating EC2 key pair...${NC}"

if aws ec2 describe-key-pairs --key-names "$KEY_NAME" --region "$AWS_REGION" 2>/dev/null; then
    echo -e "${YELLOW}⚠ Key pair already exists${NC}"
else
    aws ec2 create-key-pair \
        --key-name "$KEY_NAME" \
        --query 'KeyMaterial' \
        --output text \
        --region "$AWS_REGION" > "${KEY_NAME}.pem"

    chmod 400 "${KEY_NAME}.pem"
    echo -e "${GREEN}✓ Key pair created: ${KEY_NAME}.pem${NC}"
    echo -e "${RED}⚠ IMPORTANT: Save this file securely! You cannot download it again.${NC}"
fi

# Step 4: Get user's IP for SSH
echo ""
echo -e "${BLUE}Step 4/4: Getting your IP address...${NC}"
MY_IP=$(curl -s ifconfig.me)
echo -e "${GREEN}✓ Your IP: ${MY_IP}${NC}"

# Create terraform.tfvars
echo ""
echo -e "${BLUE}Creating terraform.tfvars...${NC}"

TFVARS_PATH="../terraform/environments/free-tier/terraform.tfvars"

cat > "$TFVARS_PATH" << EOF
# Sentra Free Tier Configuration
# Generated by setup-free-tier.sh

aws_region        = "${AWS_REGION}"
key_name          = "${KEY_NAME}"
ssh_allowed_cidrs = ["${MY_IP}/32"]

# Fill in your Supabase credentials:
supabase_url = "REPLACE_WITH_YOUR_SUPABASE_URL"
supabase_key = "REPLACE_WITH_YOUR_SUPABASE_KEY"

# Your GitHub username:
github_org = "REPLACE_WITH_YOUR_GITHUB_USERNAME"
EOF

echo -e "${GREEN}✓ terraform.tfvars created${NC}"

# Summary
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║   Setup Complete!                          ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo ""
echo "1. Edit terraform.tfvars with your Supabase credentials:"
echo -e "   ${BLUE}nano $TFVARS_PATH${NC}"
echo ""
echo "2. Deploy infrastructure:"
echo -e "   ${BLUE}cd terraform/environments/free-tier${NC}"
echo -e "   ${BLUE}terraform init${NC}"
echo -e "   ${BLUE}terraform plan${NC}"
echo -e "   ${BLUE}terraform apply${NC}"
echo ""
echo "3. Add GitHub Secrets (Settings → Secrets → Actions):"
echo "   - AWS_ROLE_ARN: (from terraform output)"
echo "   - EC2_INSTANCE_ID: (from terraform output)"
echo "   - EC2_PUBLIC_IP: (from terraform output)"
echo ""
echo "4. Push code to trigger deployment!"
echo ""
echo -e "${GREEN}Free Tier Limits:${NC}"
echo "  • EC2 t2.micro: 750 hours/month (first year)"
echo "  • EBS: 30 GB"
echo "  • ECR: 500 MB"
echo "  • Data transfer: 1 GB/month outbound"
